baseURL: "https://stefanopoma.com/"
title: "Stefano Poma"
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Stefano Poma"
  description: "Personal website and blog of Stefano Poma - Product Marketing Professional and Technology Enthusiast"
  keywords: [Product Marketing, Technology, Digital Marketing, Blog, Portfolio]
  author: Stefano
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true
    title: "Stefano Poma"
    subtitle: "Product Marketing Professional | Technology Enthusiast"
    # Add your profile picture in /images/profile.jpg or update the imageUrl with your preferred image
    #imageUrl: "/images/profile.jpg"
    #imageWidth: 120
    #imageHeight: 120
    #imageTitle: "Stefano Poma"
    buttons:
      - name: Blog
        url: posts
      - name: Projects
        url: projects
      - name: About
        url: about

  # home-info mode
  homeInfoParams:
    Title: "Welcome to my corner of the web 👋"
    Content: "I'm Stefano, a product marketing professional passionate about technology and innovation. Here I share my thoughts, projects, and experiences in tech and digital marketing."

  socialIcons:
    - name: github
      url: "https://github.com/stefanopoma"
    - name: linkedin
      url: "https://linkedin.com/in/stefanopoma"
    - name: mastodon
      url: "https://mastodon.social/@stefanopoma"
    # Add or remove social icons as needed

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/stefanopoma/hugopaper/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
